version:  "3.9"
services:
  mongo:
   environment:
   - MONGO_INITDB_ROOT_USERNAME=root
   - MONGO_INITDB_ROOT_PASSWORD=password 
   volumes:
     - mongodb:/data/db
   ports:
    - 27017:27017
  employee_api:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=password
    command: npm run dev