version: "3.9"

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: always
    
  employee_api:
    build: .
    image: abasjuno/employee_api 
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://root:password@mongo:27017?authSource=admin  
    depends_on:
      - mongo
  

volumes:
  mongodb:
